<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net462;net8.0</TargetFrameworks>
    <Version>4.6.3</Version>
    <Description>SD.IdentitySystem 身份认证系统服务接口</Description>
  </PropertyGroup>

  <ItemGroup Condition="$(TargetFramework.Equals('net462'))">
    <Reference Include="System.ServiceModel" />
  </ItemGroup>

  <ItemGroup Condition="$(TargetFramework.Equals('net8.0'))">
    <PackageReference Include="System.ServiceModel.Primitives" Version="8.1.2" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SD.Infrastructure" Version="3.8.3" />
  </ItemGroup>
</Project>
