<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SD.Common" Version="3.4.1" />
    <PackageReference Include="SD.Toolkits.Mapper" Version="1.2.1" />
    <PackageReference Include="SD.Infrastructure" Version="3.8.3" />
    <PackageReference Include="SD.IdentitySystem.IAppService" Version="4.6.3" />
  </ItemGroup>
</Project>
