<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <IsPackable>False</IsPackable>
    <UseWPF>True</UseWPF>
    <ApplicationIcon>favicon.ico</ApplicationIcon>
    <Description>SD.IdentitySystem 数据导入工具</Description>
  </PropertyGroup>

  <PropertyGroup>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>Full</DebugType>
    <DebugSymbols>True</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="favicon.ico" />
    <None Update="Content\Datas\IdentitySystem.xls">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.ServiceModel" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BusyIndicator" Version="1.9.0">
      <ExcludeAssets>contentFiles</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="FluentWPF" Version="0.10.2" />
    <PackageReference Include="SkiaSharp" Version="3.119.4" />
    <PackageReference Include="MrAdvice" Version="2.20.6" />
    <PackageReference Include="SD.Common" Version="4.0.2" />
    <PackageReference Include="SD.Toolkits.Json" Version="4.0.2" />
    <PackageReference Include="SD.Toolkits.Excel" Version="4.0.2" />
    <PackageReference Include="SD.IOC.Core" Version="1.4.2" />
    <PackageReference Include="SD.Infrastructure" Version="4.0.2" />
    <PackageReference Include="SD.Infrastructure.WPF" Version="4.0.2" />
    <PackageReference Include="SD.Infrastructure.WPF.Caliburn" Version="4.0.2" />
    <PackageReference Include="SD.IdentitySystem.IAppService" Version="4.7.2" />
    <PackageReference Include="SD.IdentitySystem.WCF.Authentication.Common" Version="4.7.2" />
  </ItemGroup>
</Project>
