<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net462;net8.0;net10.0</TargetFrameworks>
    <Description>SD.IdentitySystem WCF身份认证组件 - 通用客户端</Description>
  </PropertyGroup>

  <ItemGroup Condition="$(TargetFramework.Equals('net462'))">
    <Reference Include="System.ServiceModel" />
  </ItemGroup>

  <ItemGroup Condition="$(TargetFramework.Equals('net8.0'))">
    <PackageReference Include="System.ServiceModel.Primitives" Version="8.1.2" />
  </ItemGroup>

  <ItemGroup Condition="$(TargetFramework.Equals('net10.0'))">
    <PackageReference Include="System.ServiceModel.Primitives" Version="10.0.652802" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="SD.Infrastructure" Version="4.0.2" />
  </ItemGroup>
</Project>
