<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MrAdvice" Version="2.20.6" />
    <PackageReference Include="SD.Common" Version="4.0.2" />
    <PackageReference Include="SD.Toolkits.Recursion" Version="4.0.2" />
    <PackageReference Include="SD.Infrastructure" Version="4.0.2" />
    <PackageReference Include="SD.Infrastructure.AOP" Version="4.0.2" />
  </ItemGroup>
</Project>
