<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MrAdvice" Version="2.19.1" />
    <PackageReference Include="SD.Common" Version="4.0.0" />
    <PackageReference Include="SD.Toolkits.Recursion" Version="4.0.0" />
    <PackageReference Include="SD.Infrastructure" Version="4.0.0" />
    <PackageReference Include="SD.Infrastructure.AOP" Version="4.0.0" />
  </ItemGroup>
</Project>
